CREATE DATABASE IF NOT EXISTS mysns_1
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE mysns_1;

CREATE TABLE IF NOT EXISTS user (
    id VARCHAR(128) PRIMARY KEY,
    password VARCHAR(32),
    name VARCHAR(32),
    address VARCHAR(255),
    birth DATE,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS feed (
    no INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(128),
    content VARCHAR(4096),
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    images VARCHAR(255),
);
CREATE TABLE IF NOT EXISTS Comment (
    comment_id INT AUTO_INCREMENT PRIMARY KEY,
    feed_no INT UNSIGNED,
    user_id VARCHAR(128),
    content TEXT,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (feed_no) REFERENCES feed(no),
    FOREIGN KEY (user_id) REFERENCES user(id)
);
